name: Cainiao Scraper (cron)

on:
  schedule:
    - cron: "0 */2 * * *"   # hər 2 saatda bir
  workflow_dispatch: {}      # əl ilə də işə sala bilərsən

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install deps
        run: npm ci

      - name: Run scraper
        run: node scraper.js
